# Generated by Django 5.2 on 2025-04-17 14:16

import apps.dashboard.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_userpersonalinfo_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRUD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('images', models.ImageField(blank=True, default='Default_Images/default.jpg', null=True, upload_to=apps.dashboard.models.user_profile_upload_path)),
                ('full_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('about_company', models.TextField(blank=True, null=True)),
                ('website_company', models.URLField(blank=True, null=True)),
                ('linkedin_company', models.URLField(blank=True, null=True)),
                ('company_type', models.CharField(choices=[('Startup', 'Startup'), ('MNC', 'MNC'), ('Government', 'Government'), ('Private', 'Private')], default='Private', max_length=110)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_infomations', to='users.user')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
