# Generated by Django 5.2 on 2025-04-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAR_MODEL', models.CharField(max_length=255)),
                ('CAR_MADE', models.CharField(max_length=255)),
                ('CAR_PRICE', models.FloatField()),
            ],
        ),
    ]
