# Generated by Django 5.2 on 2025-04-08 19:50

import apps.users.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonalInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(default='Default_Images/user_default_profile.png', upload_to=apps.users.models.user_profile_upload_path)),
                ('first_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
