# Generated by Django 5.2 on 2025-04-09 09:07

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpersonalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='profile_picture',
            field=models.ImageField(default='Default_Images/default.jpg', upload_to=apps.users.models.user_profile_upload_path),
        ),
    ]
